export enum UtilText {
  LISTA_REPORTE_VERTICAL = 1,
  LISTA_REPORTE_HORIZONTAL = 2,

  /*TEXTOS GRAFICO RESUMEN*/
  TITLE_GRAFICO_INGRESO = "INGRESOS POR SALA",
  TITLE_GRAFICO_ESCRITO = "ESCRITOS POR SALA",
  TITLE_GRAFICO_PROGRAMADOS = "PROGRAMADOS POR SALA",
  TITLE_GRAFICO_SENTILLO_FALLO = "PENDIENTE FALLO",
  TITLE_GRAFICO_PROGRAMADOD_VS_PENDI = "PENDIENTES VS PROGRAMADOS",

  TXT_INGRESOS = "Ingresos",
  TXT_PROGRAMADOS = "Programados",
  TXT_ESCRITOS = "Escritos",

  TXT_R1_TITULO_TABLA01 = "REPORTE DE INGRESO POR RECURSOS",
  TXT_R1_TITULO_TABLA02 = "REPORTE DE INGRESO POR CORTE PROCEDENCIA",

  TXT_R2_TITULO_TABLA01 = "REPORTE DE PROGRAMACION POR PONENTE",
  TXT_R2_TITULO_TABLA02 = "REPORTE PROGRAMADOS PENDIENTE DE ATENCION",
  TXT_R2_TITULO_TABLA03 = "REPORTE DETALLADO DE PENDIENTE DE ATENCION",

  TXT_R3_TITULO_TABLA01 = "REPORTE DE ESCRITOS POR TIPO DOCUMENTO",
  TXT_R3_TITULO_TABLA02 = "REPORTE DE ESCRITOS POR SITUACION",

  TXT_R4_TITULO_TABLA01 = "REPORTE DE PENDIENTE DE FALLO POR PONENTE",
  TXT_R4_TITULO_TABLA02 = "REPORTE DE PENDIENTE DE FALLO POR PONENTE DETALLADO",

  TXT_R5_TITULO_TABLA01 = "REPORTE DE MESA DE PARTES 001",
  TXT_R5_TITULO_TABLA02 = "REPORTE DE MESA DE PARTES 002",


  TIPO_GRAFICO_INGRESOS = 1,
  TIPO_GRAFICO_PROGRAMADOS = 2,
  TIPO_GRAFICO_ESCRITOS = 3,
  TIPO_GRAFICO_PENDIENTE_FALLO = 4,
  TIPO_GRAFICO_MESA_PARTES = 5,
  TIPO_GRAFICO_PENDIENTE_VS_PROGRAMADOS = 111,
}
